### ISSUE TITLE
Merging Models

### ISSUE THREAD

**Issue by synerp** [ajmnz/prisma-import#27]
Hi there, 

I am trying out prisma-import as a replacement for Aurora.  I am not sure what I am doing wrong.  

base.prisma
```
import {Person} from "./Person"

datasource db {
  provider             = "mysql"
  url                  = env("GPerson-DATABASE_URL")
  relationMode = "prisma"
}

generator client {
  provider        = "prisma-client-js"
  output          = env("GPerson-Prisma_Client_Dir")
}

model Person {
  id       String  @id
  password String? /// This is defined here because I dont want it in other schemas that import Person
}

```
Person.prisma
```
model Person {
  id                            String                                              @id
  createdAt                     DateTime                                            @default(now())
  updatedAt                     DateTime?                                           @updatedAt
  first_name                    String
  last_name                     String
 }
```

I get the following errors in base.prisma
![image](https://user-images.githubusercontent.com/103918339/212202385-360f0e0f-7f7d-4855-aa33-3587bf5c9935.png)

When I run prisma-import on base.prisma I get the following: 
```
//
// Autogenerated by `prisma-import`
// Any modifications will be overwritten on subsequent runs.
//

//
// base.prisma
//

datasource db {
  provider     = "mysql"
  url          = env("GPerson-DATABASE_URL")
  relationMode = "prisma"
}

generator client {
  provider = "prisma-client-js"
  output   = env("GPerson-Prisma_Client_Dir")
}

model Person {
  id       String  @id
  password String? /// This is defined here because I dont want it in other schemas that import Person
}
```

So 2 things, why the errors in VSCode about multiple db's and why arn't the fields like first_name from Person.prisma showing up in the merged Person model?

Thanks

**Comment by ajmnz** [comment]
Hi,

About the duplicate `datasource` issue: The VSCode extension doesn't know which is your "output schema", so it needs a little help to exclude it. There's the `prisma.import.exclude` configuration available that you can set up in your VSCode settings to exclude certain schemas from being picked up by the extension. Supposing that your output schema is `schema.prisma`, you could add a glob path similar to `"prisma.import.exclude": ["**/schema.prisma"]`.

If the issue persists after setting the configuration, make sure that you don't have another `datasource` defined in another schema (that's not excluded by the configuration), since Prisma doesn't allow multiple datasources.

---

About the model-merging issue: The CLI doesn't "combine" models, it just looks up all the schemas in the glob you pass to it and then proceeds to merge them (the schemas, not the models) into one single schema that Prisma can understand. The CLI doesn't care about imports —it doesn't perform any kind of resolution—, it just gets a glob path and appends all schemas together, stripping the import statements.

The result you should expect would be something like the following:

```prisma
//
// Autogenerated by `prisma-import`
// Any modifications will be overwritten on subsequent runs.
//

//
// base.prisma
//

datasource db {
  provider     = "mysql"
  url          = env("GPerson-DATABASE_URL")
  relationMode = "prisma"
}

generator client {
  provider = "prisma-client-js"
  output   = env("GPerson-Prisma_Client_Dir")
}

model Person {
  id       String  @id
  password String? /// This is defined here because I dont want it in other schemas that import Person
}

//
// person.prisma
//

model Person {
  id                            String                                              @id
  createdAt                     DateTime                                            @default(now())
  updatedAt                     DateTime?                                           @updatedAt
  first_name                    String
  last_name                     String
 }
```

Which is indeed invalid Prisma syntax, since there's a duplicate model `Person`. What you're trying to do is not possible, and the reason why you're not seeing the `person.prisma` contents in the output might be because `person.prisma` does not satisfy the glob path you're passing to the CLI.

**Comment by synerp** [comment]
Ah I get you.  About the "not possible" part of merging the models.  Is that not possible at all or maybe I can pay you to add the feature?

**Comment by ajmnz** [comment]
By not possible, I meant that it is not possible _with the current implementation_ of the CLI. It would be possible to add it as a feature, yes, but I don't fully understand what you expect as an output when merging the `Person` model. Could you please send how you expect the output to be?

**Comment by Yiin** [comment]
Not sure if related to the OP question as their example is quite unclear, but it would be great to have a way to extend existing models. E.g.

player.prisma
```
model Player {
  id String @id
  name String @unique
}
```

inventory.prisma
```
import { Player } from './player';

extend Player {
  inventory Inventory
}

type Inventory {
  items Item[]
}

type Item {
  key String
  amount Int
}
```

final output:
```
model Player {
  id String @id
  name String @unique
  inventory Inventory
}

type Inventory {
  items Item[]
}

type Item {
  key String
  amount Int
}
```
