### ISSUE TITLE
SVCode ext: Dragging schema to new file location does not trigger file path updates in depent files

### ISSUE THREAD

**Issue by iiian** [ajmnz/prisma-import#52]
I have two schemas:

`schema.prisma`

```prisma
import { Dep } from "./module.schema"
```

`module.schema.prisma`

```prisma
...
```

When I drag `module.schema.prisma` to a new directory, say `schemas`, it does not update `schema.prisma`'s link, which should become:

```prisma
import { Dep } from "./schemas/module.schema"
```

Any ideas on how to implement this, or where to look to get started? Would be happy to help contribute.

**Comment by ajmnz** [comment]
👋 @iiian 

Yup. I didn't get to add import updates on file rename, model rename or file location change.

For the file location change, you first need to set up listeners for that event and filter those files that are not schemas with imports or schemas not imported from anywhere.

Once those listeners are in place, you want to
1. Identify which schemas the target (the file that changed location) is referencing, and update those paths within the target. I'm pretty sure there are methods within the VS Code API to read the target before and after changing location. You might need this to grab the absolute path of the imported schemas and then updating them accordingly, so you don't end up picking schemas or models from wrong files.
2. Identify which schemas import the target and update them with the new path. Again, you might want to identify them before.

For starters, event listeners are registered [in the extension](https://github.com/ajmnz/prisma-import/blob/main/packages/vscode/src/plugins/prisma-language-server/index.ts) or [in the language server](https://github.com/ajmnz/prisma-import/blob/main/packages/language-server/src/server.ts). If the Language Server API supports listening for these events, implement the listeners there. Otherwise, you will need to listen from the extension and forward the event to the language server [as seen here](https://github.com/ajmnz/prisma-import/blob/main/packages/vscode/src/plugins/prisma-language-server/index.ts#L77-L99).

Then files that might be interesting to get an idea of how everything works:
- https://github.com/ajmnz/prisma-import/blob/main/packages/language-server/src/imports.ts
- https://github.com/ajmnz/prisma-import/blob/main/packages/language-server/src/virtual-schema.ts

Keep in mind that, as I see it, this could be written without modifying barely any or any file in the codebase, since these changes should just edit schemas and should not infer on the model resolving logic.

**Comment by iiian** [comment]
I'll dig in this weekend, thanks for directions
