### ISSUE TITLE
Semantic support request: `import * from ..`

### ISSUE THREAD

**Issue by iiian** [ajmnz/prisma-import#53]
Awesome project, btw, @ajmnz 

Would be nice to split schemas up into remote parts, one thing I've always resented about prisma is the (potentially) thousands of lines long model files. It would be awesome to have a system where I could do smoething like:

```prisma
...

import * from "./path/to/model1.schema"
import * from "./path/to/model2.schema"
import * from "./path/to/model3.schema"
...
```

Again, would be happy to contribute to something like this. I don't love that the `prisma` team has taken the stance that the community is responsible for implementing this kind of functionality, but you're the first project that is offering this stuff so let's just roll with it 😂

**Comment by ajmnz** [comment]
👋 @iiian 

I like the idea of having a whole schema import because, to be honest, right now named imports are just syntactic sugar 
because in the end the CLI will end up merging all schemas together instead of reading the imports.

I like the syntax you proposed too, I think in the future we could even do stuff like `import * as enums from "./utils/enums"`.

Right now I don't have much time to implement something like this, because it might require rewriting the import parsing logic and moving it into a separate module. But I'm happy to give you directions on anything you need if you want to contribute.
